[package]
name = "the_rust_programming_language"
version = "0.1.0"
authors = ["Rodrigo Batista <rodrigo_develms@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
